### ISSUE TITLE
PyQt5 issue on windows pip install 

### ISSUE THREAD

**Issue by bforsbe** [bforsbe/OccuPy#16]
Reported by Alexandre Littiere:

I'm trying to start OccuPy (0.1.12) in powershell, but the code is returning an 
error message :

```
➜ occupy_gui
Traceback (most recent call last):
   File "c:\users\alex\anaconda3\lib\runpy.py", line 194, in 
_run_module_as_main
     return _run_code(code, main_globals, None,
   File "c:\users\alex\anaconda3\lib\runpy.py", line 87, in _run_code
     exec(code, run_globals)
   File "C:\Users\Alex\anaconda3\Scripts\occupy_gui.exe\__main__.py", 
line 7, in <module>
   File 
"c:\users\alex\anaconda3\lib\site-packages\occupy_lib\occupy.py", line 
27, in app_gui
     ui.setupUi(MainWindow)
   File 
"c:\users\alex\anaconda3\lib\site-packages\occupy_lib\occupy_gui.py", 
line 624, in setupUi
     
self.spinBox_viewSlice.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
AttributeError: 'QSpinBox' object has no attribute 'setStepType'
```

**Comment by bforsbe** [comment]
This turned out to be due to missing PyQt5, which mirrors issue #15 due to the removed explicit dependency on PyQt5 in pull-request #11. 

Will close when install instructions are up-to-date.

**Comment by bforsbe** [comment]
Also, we might omit to set the StepType of spin-boxes to be more permissive.

**Comment by AndreTomasGraca** [comment]
Björn, similar issue here on a Ubuntu 20.04 machine.

`Traceback (most recent call last):
  File "/home/angr5008/anaconda3/bin/occupy_gui", line 8, in <module>
    sys.exit(app_gui())
  File "/home/angr5008/anaconda3/lib/python3.9/site-packages/occupy_lib/occupy.py", line 27, in app_gui
    ui.setupUi(MainWindow)
  File "/home/angr5008/anaconda3/lib/python3.9/site-packages/occupy_lib/occupy_gui.py", line 624, in setupUi
    self.spinBox_viewSlice.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
AttributeError: 'QSpinBox' object has no attribute 'setStepType'
`

**Comment by bforsbe** [comment]
Thanks for reporting. Does it resolve by using 
```
pip install occupy[pyqt5]
```
to install? You might also need to enclose it in quotations as such 
```
pip install "occupy[pyqt5]"
```
