### ISSUE TITLE
ChimeraX isn't found on MacOS

### ISSUE THREAD

**Issue by asarnow** [bforsbe/OccuPy#18]
The path used to search /Applications for is not the standard install path. OccuPy looks for `/Applications/*app/chimerax`, but the binary is in `/Applications/ChimeraX-version/Contents/bin/ChimeraX`.

I made a minimal fix [here](https://github.com/bforsbe/OccuPy/commit/50b14567ed8551e822b5d03e4e83682555bda8de), if you're OK with it I can make a PR.

I would also propose to check only `ChimeraX*app` rather than all application directories as a (roughly) conventional path has to be used unless we would search more carefully.

**Comment by alisterburt** [comment]
@asarnow nice to see you around here! Change looks good to me but I'll wait for @bforsbe to weigh in

**Comment by bforsbe** [comment]
This code was written with limited testing on mac so I'm not surprised something is might be off. Has chimerax changed where it installs by default?

**Comment by asarnow** [comment]
I can't remember if/when there used to be an actual ChimeraX installer for mac, but at any rate now it's a DMG with a .app directory to copy directly to /Applications. The Python precompilation happens at the first run.

<img width="831" alt="image" src="https://github.com/bforsbe/OccuPy/assets/4052606/ee48a4ff-8ae7-4881-b203-0bb245dd28ce">

**Comment by bforsbe** [comment]
Since people tend to not update (chimmerax) to the latest version until they want some shiny new feature I think it makes sense to preserve backward compatibility, but you are right to add this new path as well then. 

Since `find_chimerax()`  only sets if not found it should be safe to do 

```
for dir in app_dirs:
    self.find_chimerax(f'{dir}/chimerax')
    self.find_chimerax(f'{dir}/Contents/bin/ChimeraX')
```
